### ISSUE TITLE
Footer: Submit button overlaps with titanweb logo

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Residential-Building-Brokers#16]
![image](https://cloud.githubusercontent.com/assets/12791909/11707811/c02b67ba-9f43-11e5-80f5-d9813fc92b25.png)

**Comment by titanguest** [comment]
Adjusted.

**Comment by ermatitan** [comment]
Not fix when validation error occurs:

![image](https://cloud.githubusercontent.com/assets/12791909/11734645/383d68b0-9ff4-11e5-8c39-7ebd222cb84d.png)

**Comment by titanguest** [comment]
All good
