### ISSUE TITLE
All page titles were not set to H1 tag.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Residential-Building-Brokers#17]
![image](https://cloud.githubusercontent.com/assets/12791909/11708187/8a838670-9f47-11e5-9ead-86866c1a156a.png)

**Comment by titanguest** [comment]
h2 changed to h1

**Comment by ermatitan** [comment]
Not fix on the pages below:
Gallery page
Featured Projects
Concept
Testimonials
Contact

**Comment by titanguest** [comment]
all good
