### ISSUE TITLE
Footer: Facebook Like button placeholder was truncated

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Residential-Building-Brokers#4]
![image](https://cloud.githubusercontent.com/assets/12791909/11419909/727336b2-9465-11e5-9156-70fc5c872fb2.png)

**Comment by titanguest** [comment]
Truncated content removed

**Comment by ermatitan** [comment]
Number of likes should be displayed.

**Comment by titanguest** [comment]
Number of likes now displayed.
