### ISSUE TITLE
Privacy page is empty.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Residential-Building-Brokers#6]
![image](https://cloud.githubusercontent.com/assets/12791909/11432548/8b86676a-94eb-11e5-9d9f-29db92f693c0.png)

**Comment by titanguest** [comment]
Privacy page actually have NO content.  Please provide.
http://residentialbrokers.stage.titanweb.com.au/wp-admin/post.php?post=39&action=edit

**Comment by ermatitan** [comment]
Maybe you can add the Titan generic privacy policy content. Thanks
https://knowledgebase.titanweb.com.au/resource-information/generic-privacy-policy

**Comment by titanguest** [comment]
Generic Privacy Policy added.
